---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: release-service
  namespace: release-service
spec:
  latestResourceSchemas:
  - md5-06f1498b5778196e58c2bc1fc88108b8.releaseplanadmissions.appstudio.redhat.com
  - md5-9959e22acaaf6d162a03980c75b93dfe.releaseplans.appstudio.redhat.com
  - md5-e3f55fb6efb4bca5c1b68c9813fe9a90.releases.appstudio.redhat.com
  - md5-a1a202cb4819f0c40034030c40f8526f.releasestrategies.appstudio.redhat.com
  permissionClaims:
  - group: appstudio.redhat.com
    identityHash: 821b74ed5dc2186de533818f7471cde5b63476ba4b0a1c65efb66e73acfaa8b3
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 821b74ed5dc2186de533818f7471cde5b63476ba4b0a1c65efb66e73acfaa8b3
    resource: components
  - group: appstudio.redhat.com
    identityHash: 821b74ed5dc2186de533818f7471cde5b63476ba4b0a1c65efb66e73acfaa8b3
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: 821b74ed5dc2186de533818f7471cde5b63476ba4b0a1c65efb66e73acfaa8b3
    resource: environments
  - group: appstudio.redhat.com
    identityHash: 821b74ed5dc2186de533818f7471cde5b63476ba4b0a1c65efb66e73acfaa8b3
    resource: applicationsnapshotenvironmentbindings
  - group: tekton.dev
    identityHash: e91b8274bdf19fff5bd7df8897a55261e9daf40d9c64c3c5d396f7d95d1c02a7
    resource: pipelineruns
