apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/openshift?ref=bfdf23f4a91352b286fb8631ed1d313eed02d61e

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: bfdf23f4a91352b286fb8631ed1d313eed02d61e
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: bfdf23f4a91352b286fb8631ed1d313eed02d61e

namespace: spi-system


patches:
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
patchesStrategicMerge:
  - delete-shared-configuration-file.yaml
