---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit-namespace
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit-buildpipelineselectors
rules:
- apiGroups:
  - "appstudio.redhat.com"
  resources:
  - buildpipelineselectors
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch