apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- role.yaml
- rolebinding.yaml

namespace: build-templates

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: build-pipelines-defaults
  literals:
  - default_build_bundle=quay.io/redhat-appstudio/build-templates-bundle:748a03507b68aa610212e8031e3301ab943a14ef
  - hacbs_build_bundle=quay.io/redhat-appstudio/build-templates-bundle:748a03507b68aa610212e8031e3301ab943a14ef
