resources:
- authorization-in-cluster.yaml
- authorization-in-kcp.yaml
- application-api.yaml
- application-service.yaml
- build-service.yaml
- enterprise-contract.yaml
- spi.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
