resources:
- gitops.yaml
- authentication.yaml
- application-api.yaml
- has.yaml
- release.yaml
- integration.yaml
- spi.yaml
- e2e-tests.yaml
- cluster-registration.yaml
- enterprise-contract.yaml
- quality-dashboard.yaml
- hac-pact-broker.yaml
- build-service.yaml
- jvm-build-service.yaml
- pipeline-service.yaml
- build-templates.yaml
- shared-resources.yaml
- monitoring-workload-in-cluster.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
